models:
  describer:
    name: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
    provider: "together"
  environment:
    name: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
    provider: "together"
  agent:
    name: "meta-llama/Meta-Llama-3.2-3B-Instruct-Turbo"
    provider: "together"
  evaluator:
    name: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
    provider: "together"

simulation:
  max_steps: 30

evaluation:
  enabled: true
  log_to_file: true
  log_path: "logs/evaluations/" 