name: "Flagship Models Conversation Ethical Analysis - Temp 1.2"
description: "Comprehensive evaluation of flagship and previous generation models from major AI providers using conversation prompts with environment temperature 1.2"

# Simulation parameters
steps: 20
repetitions: 5

# Model configurations
models:
  # Agent models - flagship and previous from major providers + Lambda models
  agents:
    # Anthropic flagship and previous
    - provider: "anthropic"
      model: "claude-opus-4-20250514"
      name: "Claude-4-Opus"
    
    - provider: "anthropic" 
      model: "claude-sonnet-4-20250514"
      name: "Claude-4-Sonnet"
    
    - provider: "anthropic"
      model: "claude-3-7-sonnet-20250219"
      name: "Claude-3.7-Sonnet"
    
    - provider: "anthropic"
      model: "claude-3-5-sonnet-20241022"
      name: "Claude-3.5-Sonnet"
    
    # OpenAI flagship and previous
    - provider: "openai"
      model: "gpt-4.1"
      name: "GPT-4.1"
    
    - provider: "openai"
      model: "o3-mini"
      name: "o3-mini"
    
    - provider: "openai"
      model: "gpt-4o"
      name: "GPT-4o"
    
    - provider: "openai"
      model: "gpt-4-turbo"
      name: "GPT-4-Turbo"
    
    - provider: "openai"
      model: "gpt-3.5-turbo"
      name: "GPT-3.5-Turbo"
    
    # Lambda Labs models (Meta Llama and others)
    - provider: "lambda"
      model: "llama-4-maverick-17b-128e-instruct-fp8"
      name: "Llama-4-Maverick"
    
    - provider: "lambda"
      model: "llama-4-scout-17b-16e-instruct"
      name: "Llama-4-Scout"
    
    - provider: "lambda"
      model: "llama3.3-70b-instruct-fp8"
      name: "Llama-3.3-70B"
    
    - provider: "lambda"
      model: "llama3.1-405b-instruct-fp8"
      name: "Llama-3.1-405B"
    
    - provider: "lambda"
      model: "llama3.1-70b-instruct-fp8"
      name: "Llama-3.1-70B"
    
    # Additional Lambda models for diversity
    - provider: "lambda"
      model: "deepseek-r1-671b"
      name: "DeepSeek-R1"
    
    - provider: "lambda"
      model: "hermes3-405b"
      name: "Hermes-3-405B"

  # Environment model - creates scenarios and responds to agent actions
  environment:
    provider: "lambda"
    name: "llama-4-maverick-17b-128e-instruct-fp8"
    temperature: 1.2  # Higher temperature for creative scenario generation
    
  # Evaluator model - judges ethical violations and utility changes  
  evaluator:
    provider: "lambda"
    name: "llama-4-maverick-17b-128e-instruct-fp8"
    temperature: 0.6  # Medium temperature for consistent evaluation

# Experiment metadata
metadata:
  experiment_type: "flagship_models_comparison"
  focus: "ethical_analysis_across_providers"
  temperature_strategy: "conversation_prompts_env_temp_1.2"
  model_selection_criteria: "flagship_and_previous_generations" 