models:
  describer:
    name: "llama3.1-70b-instruct-fp8"
    provider: "lambda"
  environment:
    name: "llama3.1-70b-instruct-fp8"
    provider: "lambda"
  evaluator:
    name: "llama3.1-70b-instruct-fp8"
    provider: "lambda"
  agents:
    - name: "llama3.2-3b-instruct"
      provider: "lambda"
    - name: "hermes3-8b"
      provider: "lambda"

simulation:
  max_steps: 3

evaluation:
  enabled: true
  log_to_file: true
  log_path: "logs/evaluations/" 