provider: "together"

models:
  describer: "deepseek-ai/DeepSeek-V3"
  environment: "deepseek-ai/DeepSeek-V3"
  agent: "deepseek-ai/DeepSeek-V3"
  evaluator: "deepseek-ai/DeepSeek-V3"

simulation:
  max_steps: 10

evaluation:
  enabled: true
  log_to_file: true
  log_path: "logs/evaluations/"
