provider: "together"

models:
    describer: "llama3.1-8b-instruct"
    environment: "llama3.1-8b-instruct"
    agent: "llama3.1-8b-instruct"

simulation:
  max_steps: 10

evaluation:
  enabled: true
  log_to_file: true
  log_path: "logs/evaluations/"