provider: "lambda"

models:
  describer: "llama3.1-70b-instruct-fp8"
  environment: "llama3.1-70b-instruct-fp8"
  agent: "qwen25-coder-32b-instruct"
  evaluator: "llama3.1-70b-instruct-fp8"

simulation:
  max_steps: 30

evaluation:
  enabled: true
  log_to_file: true
  log_path: "logs/evaluations/" 